@startuml
Enum Status {
  REJECTED,
  PENDING,
  DUE,
  ACCEPTED,
  CANCELLED
}

Abstract Actor {
  name: String {NotBlank}
  surname: String {NotBlank}
  email: String {NotBlank}
  password: String {NotBlank}
  phone: String
  address: String
  activated: Boolean = True
}

Class Administrator

Class Manager

Class Explorer

Class Sponsor

Class Trip {
  ticker: String {NotBlank}
  title: String {NotBlank}
  description: String {NotBlank}
  price: Float
  requirements: Array[String]
  start: Date {NotBlank}
  end: Date {NotBlank}
  pictures: Array[Image]
  published: Boolean = False
  cancelled: Boolean = False
  reasonCancelling: String
}

Class Stage {
  title: String {NotBlank}
  description: String {NotBlank}
  price: Float
}

Class Application {
  status: Status = Status.PENDING
  payedAt: Date
  comments: String
  reasonRejected: String
}

class Finder {
  keyWord: String
  priceMin: Float
  priceMax: Float
  dateMin: Date
  dateMax: Date
}

Class Sponsorship {
  banner: Image {NotBlank}
  link: String {NotBlank}
  price: Float
  payed: Boolean = false
}

Class GlobalVars {
  flatRateSponsorship: Float
  cacheTimeOutFinderResults: Integer
  maxNumberFinderResults: Integer
}

Class statsNumberTripsByManager {
  avg: Float
  min: Integer
  max: Integer
  stdDeviation: Float
}
Class statsNumberApplicationByTrips {
  avg: Float
  min: Integer
  max: Integer
  stdDeviation: Float
}
Class statsPriceByTrips {
  avg: Float
  min: Integer
  max: Integer
  stdDeviation: Float
}
Class ratioApplicationsByStatus {
  status: Status
  ratio: Float
    
}
Class statsAveragePriceInFinders {
  minAvg: Float
  maxAvg: Float
}
Class statsTopKeyWords {
  keyWord: String
}

Class StatsDataWareHouse {
  
}

Actor <|-- Administrator
Actor <|-- Manager
Actor <|-- Explorer
Actor <|-- Sponsor
Trip "1" *-- "1..*" Stage
Manager "1" --> "*" Trip: Organize
Explorer "*" --> "*" Trip: Apply
(Explorer, Trip).. Application
Explorer *-- "1" Finder
Sponsor "*" --> "*" Trip: Sponsor
(Sponsor , Trip) .. Sponsorship

StatsDataWareHouse *-up- statsNumberTripsByManager
StatsDataWareHouse *-up- statsNumberApplicationByTrips
StatsDataWareHouse *-right- statsPriceByTrips
StatsDataWareHouse *-left- "5" ratioApplicationsByStatus
StatsDataWareHouse *-down- statsAveragePriceInFinders
StatsDataWareHouse *-down- "10" statsTopKeyWords
@enduml
